full ipa test

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -569,13 +569,11 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
       - name: Download Presigned URLs Artifact
         uses: actions/download-artifact@v3
         with:
           name: presigned-urls
           path: presigned-urls
-
       - name: Read download URLs
         run: |
           ipa_app_url=$(cat presigned-urls/ipa_app_1.txt)
@@ -587,7 +585,6 @@ jobs:
           entitlements_file_url=$(cat presigned-urls/ipa_1_entitlements.txt)
           echo "ENTITLEMENTS_FILE=$entitlements_file_url" >> $GITHUB_OUTPUT
         id: urls
-
       - name: Set random options
         id: random-options
         run: |
@@ -595,11 +592,6 @@ jobs:
             build_with_logs=true
           else
             build_with_logs=false
-          fi
-          if [[ $((RANDOM % 2)) == 1 ]]; then
-            google_play_signing=true
-          else
-            google_play_signing=false
           fi
           build_to_test_options=("saucelabs" "None")
           build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
@@ -609,9 +601,7 @@ jobs:
           echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
           echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
           echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
-          echo "GOOGLE-PLAY-SIGNING=${google_play_signing}" >> $GITHUB_OUTPUT
         shell: bash
-
       - name: Run the Appdome plugin
         uses: Appdome/github_build-2secure@latest
         with:
@@ -626,7 +616,6 @@ jobs:
           BUILD_WITH_LOGS: ${{ steps.random-options.outputs.BUILD_WITH_LOGS }}
           OUTPUT_APP_NAME: ${{ steps.random-options.outputs.OUTPUT_APP_NAME }}
           BUILD_TO_TEST: ${{ steps.random-options.outputs.BUILD_TO_TEST }}
-
       - name: Test Environment Variables
         run: |
           # Check if APPDOME_SECURED_APP exists and is not empty
@@ -651,5 +640,149 @@ jobs:
             echo "Error: Artifact not found"
             exit 1
           fi
+  IPA1_PRIVATE_SIGNING:
+    needs: IPA1_SIGN_ON_APPDOME
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download Presigned URLs Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: presigned-urls
+          path: presigned-urls
+      - name: Read download URLs
+        run: |
+          ipa_app_url=$(cat presigned-urls/ipa_app_1.txt)
+          echo "IPA_APP=$ipa_app_url" >> $GITHUB_OUTPUT
+          mobile_provisioning_file_url=$(cat presigned-urls/ipa_1_mobile_provisioning.txt)
+          echo "MOBILE_PROVISIONING_FILE=$mobile_provisioning_file_url" >> $GITHUB_OUTPUT
+          entitlements_file_url=$(cat presigned-urls/ipa_1_entitlements.txt)
+          echo "ENTITLEMENTS_FILE=$entitlements_file_url" >> $GITHUB_OUTPUT
+        id: urls
+      - name: Set random options
+        id: random-options
+        run: |
+          if [[ $((RANDOM % 2)) == 1 ]]; then
+            build_with_logs=true
+          else
+            build_with_logs=false
+          fi
+          build_to_test_options=("saucelabs" "None")
+          build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
+          output_name_options=("None" "test_app" "test_dir/test_app" "test_dir/test_app.aab" "test_app.apk")
+          output_name_index=$((RANDOM % ${#build_to_test_options[@]}))
 
+          echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
+          echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
+          echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
+        shell: bash
+      - name: Run the Appdome plugin
+        uses: Appdome/github_build-2secure@latest
+        with:
+          APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
+          SIGN_OPTIONS: "PRIVATE_SIGNING"
+          APP_FILE: ${{ steps.urls.outputs.IPA_APP }}
+          MOBILE_PROVISION_PROFILE_FILE: ${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE }}
+          ENTITLEMENTS_FILE: ${{ steps.urls.outputs.ENTITLEMENTS_FILE }}
+          FUSION_SET_ID: ${{secrets.APPDOME_IOS_FUSION_SET_ID}}
+          BUILD_WITH_LOGS: ${{ steps.random-options.outputs.BUILD_WITH_LOGS }}
+          OUTPUT_APP_NAME: ${{ steps.random-options.outputs.OUTPUT_APP_NAME }}
+          BUILD_TO_TEST: ${{ steps.random-options.outputs.BUILD_TO_TEST }}
+      - name: Test Environment Variables
+        run: |
+          # Check if APPDOME_SECURED_APP exists and is not empty
+          if [ -n "${{ env.APPDOME_SECURED_APP }}" ]; then
+            echo "APPDOME_SECURED_APP exists and is not empty"
+          else
+            echo "Error: APPDOME_SECURED_APP is missing or empty"
+            exit 1
+          fi
 
+      - name: download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: workflow-artifacts
+          path: ${{ github.workspace }}/downloaded-artifact
+      - name: Check Artifact
+        run: |
+          if [ -d "${{ github.workspace }}/downloaded-artifact" ]; then
+            echo "Artifact exists"
+            ls ${{ github.workspace }}/downloaded-artifact
+          else
+            echo "Error: Artifact not found"
+            exit 1
+          fi
+  IPA1_AUTO_DEV_SIGNING:
+    needs: IPA1_PRIVATE_SIGNING
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download Presigned URLs Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: presigned-urls
+          path: presigned-urls
+      - name: Read download URLs
+        run: |
+          ipa_app_url=$(cat presigned-urls/ipa_app_1.txt)
+          echo "IPA_APP=$ipa_app_url" >> $GITHUB_OUTPUT
+          mobile_provisioning_file_url=$(cat presigned-urls/ipa_1_mobile_provisioning.txt)
+          echo "MOBILE_PROVISIONING_FILE=$mobile_provisioning_file_url" >> $GITHUB_OUTPUT
+          entitlements_file_url=$(cat presigned-urls/ipa_1_entitlements.txt)
+          echo "ENTITLEMENTS_FILE=$entitlements_file_url" >> $GITHUB_OUTPUT
+        id: urls
+      - name: Set random options
+        id: random-options
+        run: |
+          if [[ $((RANDOM % 2)) == 1 ]]; then
+            build_with_logs=true
+          else
+            build_with_logs=false
+          fi
+          build_to_test_options=("saucelabs" "None")
+          build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
+          output_name_options=("None" "test_app" "test_dir/test_app" "test_dir/test_app.aab" "test_app.apk")
+          output_name_index=$((RANDOM % ${#build_to_test_options[@]}))
+
+          echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
+          echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
+          echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
+        shell: bash
+      - name: Run the Appdome plugin
+        uses: Appdome/github_build-2secure@latest
+        with:
+          APPDOME_API_TOKEN: ${{secrets.APPDOME_API_KEY}}
+          SIGN_OPTIONS: "AUTO_DEV_SIGNING"
+          APP_FILE: ${{ steps.urls.outputs.IPA_APP }}
+          MOBILE_PROVISION_PROFILE_FILE: ${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE }}
+          ENTITLEMENTS_FILE: ${{ steps.urls.outputs.ENTITLEMENTS_FILE }}
+          FUSION_SET_ID: ${{secrets.APPDOME_IOS_FUSION_SET_ID}}
+          BUILD_WITH_LOGS: ${{ steps.random-options.outputs.BUILD_WITH_LOGS }}
+          OUTPUT_APP_NAME: ${{ steps.random-options.outputs.OUTPUT_APP_NAME }}
+          BUILD_TO_TEST: ${{ steps.random-options.outputs.BUILD_TO_TEST }}
+      - name: Test Environment Variables
+        run: |
+          # Check if APPDOME_SECURED_APP exists and is not empty
+          if [ -n "${{ env.APPDOME_SECURED_APP }}" ]; then
+            echo "APPDOME_SECURED_APP exists and is not empty"
+          else
+            echo "Error: APPDOME_SECURED_APP is missing or empty"
+            exit 1
+          fi
+
+      - name: download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: workflow-artifacts
+          path: ${{ github.workspace }}/downloaded-artifact
+      - name: Check Artifact
+        run: |
+          if [ -d "${{ github.workspace }}/downloaded-artifact" ]; then
+            echo "Artifact exists"
+            ls ${{ github.workspace }}/downloaded-artifact
+          else
+            echo "Error: Artifact not found"
+            exit 1
+          fi
