add second ipa, with 3 mobile provisioning files

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -703,3 +703,218 @@ jobs:
             echo "Error: Artifact not found"
             exit 1
           fi
+
+  IPA2_SIGN_ON_APPDOME:
+    needs: Presign_URLs
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download Presigned URLs Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: presigned-urls
+          path: presigned-urls
+      - name: Read download URLs
+        run: |
+          ipa_app_url=$(cat presigned-urls/ipa_app_2.txt)
+          echo "IPA_APP=$ipa_app_url" >> $GITHUB_OUTPUT
+          certificate_file_url=$(cat presigned-urls/certificate_file.txt)
+          echo "CERTIFICATE_FILE=$certificate_file_url" >> $GITHUB_OUTPUT
+          for i in {1..3}; do
+            mobile_provisioning_file_url=$(cat presigned-urls/ipa_2_mobile_provisioning_$i.txt)
+            echo "MOBILE_PROVISIONING_FILE_$i=$mobile_provisioning_file_url" >> $GITHUB_OUTPUT
+            entitlements_file_url=$(cat presigned-urls/ipa_2_entitlements_$i.txt)
+            echo "ENTITLEMENTS_FILE_$i=$entitlements_file_url" >> $GITHUB_OUTPUT
+          done
+        id: urls
+      - name: Set random options
+        id: random-options
+        run: |
+          if [[ $((RANDOM % 2)) == 1 ]]; then
+            build_with_logs=true
+          else
+            build_with_logs=false
+          fi
+          build_to_test_options=("saucelabs" "None")
+          build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
+          output_name_options=("None" "test_app" "test_dir/test_app" "test_dir/test_app.aab" "test_app.apk")
+          output_name_index=$((RANDOM % ${#build_to_test_options[@]}))
+
+          echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
+          echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
+          echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Run the Appdome plugin
+        uses: jenseng/dynamic-uses@v1
+        with:
+          uses: Appdome/github_build-2secure@${{ github.ref_name }}
+          with: '{ "APPDOME_API_TOKEN": "${{secrets.APPDOME_API_KEY}}", "SIGN_OPTIONS": "SIGN_ON_APPDOME", "APP_FILE": "${{ steps.urls.outputs.IPA_APP }}", "CERTIFICATE_FILE": "${{ steps.urls.outputs.CERTIFICATE_FILE }}", "CERTIFICATE_PASSWORD": "${{secrets.APPDOME_CERTIFICATE_PASSWORD}}", "MOBILE_PROVISION_PROFILE_FILE": "${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_1 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_2 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_3 }}", "ENTITLEMENTS_FILE": "${{ steps.urls.outputs.ENTITLEMENTS_FILE_1 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_2 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_3 }}", "FUSION_SET_ID": "${{secrets.APPDOME_IOS_FUSION_SET_ID}}", "BUILD_WITH_LOGS": "${{ steps.random-options.outputs.BUILD_WITH_LOGS }}", "OUTPUT_APP_NAME": "${{ steps.random-options.outputs.OUTPUT_APP_NAME }}", "BUILD_TO_TEST": "${{ steps.random-options.outputs.BUILD_TO_TEST }}" }'
+
+      - name: Test Environment Variables
+        run: |
+          # Check if APPDOME_SECURED_APP exists and is not empty
+          if [ -n "${{ env.APPDOME_SECURED_APP }}" ]; then
+            echo "APPDOME_SECURED_APP exists and is not empty"
+          else
+            echo "Error: APPDOME_SECURED_APP is missing or empty"
+            exit 1
+          fi
+
+      - name: download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: workflow-artifacts
+          path: ${{ github.workspace }}/downloaded-artifact
+      - name: Check Artifact
+        run: |
+          if [ -d "${{ github.workspace }}/downloaded-artifact" ]; then
+            echo "Artifact exists"
+            ls ${{ github.workspace }}/downloaded-artifact
+          else
+            echo "Error: Artifact not found"
+            exit 1
+          fi
+
+  IPA2_PRIVATE_SIGNING:
+    needs: IPA2_SIGN_ON_APPDOME
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download Presigned URLs Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: presigned-urls
+          path: presigned-urls
+      - name: Read download URLs
+        run: |
+          ipa_app_url=$(cat presigned-urls/ipa_app_2.txt)
+          echo "IPA_APP=$ipa_app_url" >> $GITHUB_OUTPUT
+          for i in {1..3}; do
+            mobile_provisioning_file_url=$(cat presigned-urls/ipa_2_mobile_provisioning_$i.txt)
+            echo "MOBILE_PROVISIONING_FILE_$i=$mobile_provisioning_file_url" >> $GITHUB_OUTPUT
+            entitlements_file_url=$(cat presigned-urls/ipa_2_entitlements_$i.txt)
+            echo "ENTITLEMENTS_FILE_$i=$entitlements_file_url" >> $GITHUB_OUTPUT
+          done
+        id: urls
+      - name: Set random options
+        id: random-options
+        run: |
+          if [[ $((RANDOM % 2)) == 1 ]]; then
+            build_with_logs=true
+          else
+            build_with_logs=false
+          fi
+          build_to_test_options=("saucelabs" "None")
+          build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
+          output_name_options=("None" "test_app" "test_dir/test_app" "test_dir/test_app.aab" "test_app.apk")
+          output_name_index=$((RANDOM % ${#build_to_test_options[@]}))
+
+          echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
+          echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
+          echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Run the Appdome plugin
+        uses: jenseng/dynamic-uses@v1
+        with:
+          uses: Appdome/github_build-2secure@${{ github.ref_name }}
+          with: '{ "APPDOME_API_TOKEN": "${{secrets.APPDOME_API_KEY}}", "SIGN_OPTIONS": "PRIVATE_SIGNING", "APP_FILE": "${{ steps.urls.outputs.IPA_APP }}", "MOBILE_PROVISION_PROFILE_FILE": "${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_1 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_2 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_3 }}", "ENTITLEMENTS_FILE": "${{ steps.urls.outputs.ENTITLEMENTS_FILE_1 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_2 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_3 }}", "FUSION_SET_ID": "${{secrets.APPDOME_IOS_FUSION_SET_ID}}", "BUILD_WITH_LOGS": "${{ steps.random-options.outputs.BUILD_WITH_LOGS }}", "OUTPUT_APP_NAME": "${{ steps.random-options.outputs.OUTPUT_APP_NAME }}", "BUILD_TO_TEST": "${{ steps.random-options.outputs.BUILD_TO_TEST }}" }'
+
+      - name: Test Environment Variables
+        run: |
+          # Check if APPDOME_SECURED_APP exists and is not empty
+          if [ -n "${{ env.APPDOME_SECURED_APP }}" ]; then
+            echo "APPDOME_SECURED_APP exists and is not empty"
+          else
+            echo "Error: APPDOME_SECURED_APP is missing or empty"
+            exit 1
+          fi
+
+      - name: download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: workflow-artifacts
+          path: ${{ github.workspace }}/downloaded-artifact
+      - name: Check Artifact
+        run: |
+          if [ -d "${{ github.workspace }}/downloaded-artifact" ]; then
+            echo "Artifact exists"
+            ls ${{ github.workspace }}/downloaded-artifact
+          else
+            echo "Error: Artifact not found"
+            exit 1
+          fi
+
+  IPA2_AUTO_DEV_SIGNING:
+    needs: IPA2_PRIVATE_SIGNING
+    runs-on: 'ubuntu-latest'
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download Presigned URLs Artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: presigned-urls
+          path: presigned-urls
+      - name: Read download URLs
+        run: |
+          ipa_app_url=$(cat presigned-urls/ipa_app_2.txt)
+          echo "IPA_APP=$ipa_app_url" >> $GITHUB_OUTPUT
+          for i in {1..3}; do
+            mobile_provisioning_file_url=$(cat presigned-urls/ipa_2_mobile_provisioning_$i.txt)
+            echo "MOBILE_PROVISIONING_FILE_$i=$mobile_provisioning_file_url" >> $GITHUB_OUTPUT
+            entitlements_file_url=$(cat presigned-urls/ipa_2_entitlements_$i.txt)
+            echo "ENTITLEMENTS_FILE_$i=$entitlements_file_url" >> $GITHUB_OUTPUT
+          done
+        id: urls
+      - name: Set random options
+        id: random-options
+        run: |
+          if [[ $((RANDOM % 2)) == 1 ]]; then
+            build_with_logs=true
+          else
+            build_with_logs=false
+          fi
+          build_to_test_options=("saucelabs" "None")
+          build_to_test_index=$((RANDOM % ${#build_to_test_options[@]}))
+          output_name_options=("None" "test_app" "test_dir/test_app" "test_dir/test_app.aab" "test_app.apk")
+          output_name_index=$((RANDOM % ${#build_to_test_options[@]}))
+
+          echo "BUILD_WITH_LOGS=${build_with_logs}" >> $GITHUB_OUTPUT
+          echo "OUTPUT_APP_NAME=${output_name_options[$output_name_index]}" >> $GITHUB_OUTPUT
+          echo "BUILD_TO_TEST=${build_to_test_options[$build_to_test_index]}" >> $GITHUB_OUTPUT
+        shell: bash
+
+      - name: Run the Appdome plugin
+        uses: jenseng/dynamic-uses@v1
+        with:
+          uses: Appdome/github_build-2secure@${{ github.ref_name }}
+          with: '{ "APPDOME_API_TOKEN": "${{secrets.APPDOME_API_KEY}}", "SIGN_OPTIONS": "AUTO_DEV_SIGNING", "APP_FILE": "${{ steps.urls.outputs.IPA_APP }}", "MOBILE_PROVISION_PROFILE_FILE": "${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_1 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_2 }},${{ steps.urls.outputs.MOBILE_PROVISIONING_FILE_3 }}", "ENTITLEMENTS_FILE": "${{ steps.urls.outputs.ENTITLEMENTS_FILE_1 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_2 }},${{ steps.urls.outputs.ENTITLEMENTS_FILE_3 }}", "FUSION_SET_ID": "${{secrets.APPDOME_IOS_FUSION_SET_ID}}", "BUILD_WITH_LOGS": "${{ steps.random-options.outputs.BUILD_WITH_LOGS }}", "OUTPUT_APP_NAME": "${{ steps.random-options.outputs.OUTPUT_APP_NAME }}", "BUILD_TO_TEST": "${{ steps.random-options.outputs.BUILD_TO_TEST }}" }'
+
+      - name: Test Environment Variables
+        run: |
+          # Check if APPDOME_SECURED_APP exists and is not empty
+          if [ -n "${{ env.APPDOME_SECURED_APP }}" ]; then
+            echo "APPDOME_SECURED_APP exists and is not empty"
+          else
+            echo "Error: APPDOME_SECURED_APP is missing or empty"
+            exit 1
+          fi
+
+      - name: download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: workflow-artifacts
+          path: ${{ github.workspace }}/downloaded-artifact
+      - name: Check Artifact
+        run: |
+          if [ -d "${{ github.workspace }}/downloaded-artifact" ]; then
+            echo "Artifact exists"
+            ls ${{ github.workspace }}/downloaded-artifact
+          else
+            echo "Error: Artifact not found"
+            exit 1
+          fi
